### ISSUE TITLE
Terser

### ISSUE THREAD

**Issue by iliakan** [javascript-ru/webpack-screencast#4]
У Terser есть клёвые настройки типа drop_console или pure_funcs для более тонкого удаления ненужных функций

**Comment by ifedyukin** [comment]
Ссылки по теме:
* https://davidwalsh.name/compress-uglify
* https://webpack.js.org/plugins/terser-webpack-plugin/

**Comment by iliakan** [comment]
А я думал, что Terser встроен в последний Webpack?

**Comment by ifedyukin** [comment]
@iliakan, нет, он как отдельный плагин идет. В [доке](https://webpack.js.org/plugins/terser-webpack-plugin/):
> This module requires a minimum of Node v6.9.0 and Webpack v4.0.0.
> To begin, you'll need to install terser-webpack-plugin
