### ISSUE TITLE
Предложения по темам

### ISSUE THREAD

**Issue by wsjscss** [javascript-ru/webpack-screencast#7]
Огромное спасибо за то что взялись за скринкаст Webpack! С нетерпением жду. Вот список тем, которые были бы полезны всем, кто использует webpack и мне в частности

**Уменьшаем размер бандла**
1. Проверяем размер бандла с Webpack Bundle Analyzer
2. Минификация: UglifyJS, Css-nano, SVGO
3.  Dead code elimination (uglifyJS)
4. Tree shaking. Рассказать как правильно его использовать, в каких случаях он работает, а когда не работает. Сайд эффекты

**Ускорение сборки**
1. Параллелизация сборки (HappyPackPlugin, thread-loader)
2. Кэширование (cache-loader, HardSourcePlugin)
3. Не записывать файлы на диск в режиме DEV, а работать с ними из памяти

**Comment by ifedyukin** [comment]
Добавил простенький пример, рассказать про это точно нужно.
@wsjscss, cпасибо!
