### ISSUE TITLE
Ветка Entries не запускает сервер

### ISSUE THREAD

**Issue by wsjscss** [javascript-ru/webpack-screencast#9]
Как воспроизвести баг:

1. Скачал ветку `entries` архивом и распаковал
2. Запустил `npm install`
3. Запустил `npm run dev`
4. Перехожу в браузере по адресу `localhost:8000` и не работает сайт как будто сервер не запущен. 

В ветке `master` все те же шаги работают как надо

**Comment by ifedyukin** [comment]
@wsjscss в ветке `entries` нет dev-сервера, там webpack работает в watch-моде и просто ребилдует статику, чтобы сразу на нескольких html-ках смотреть, а эту статику уже раздает ws (`npm run serve`).

Плюс ко всему, эта ветка не основная а для примера, так что в рамках задачи текущее поведение вполне подходит.
